# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: central.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcentral.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x0c\x63ommon.proto\"-\n\x18GetLinkCodeRecordRequest\x12\x11\n\tlink_code\x18\x01 \x01(\t2l\n\x07\x43\x65ntral\x12\x61\n\x11GetLinkCodeRecord\x12\x19.GetLinkCodeRecordRequest\x1a\x0f.LinkCodeRecord\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/linkcode/{link_code}b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'central_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CENTRAL.methods_by_name['GetLinkCodeRecord']._options = None
  _CENTRAL.methods_by_name['GetLinkCodeRecord']._serialized_options = b'\202\323\344\223\002\032\022\030/v1/linkcode/{link_code}'
  _GETLINKCODERECORDREQUEST._serialized_start=61
  _GETLINKCODERECORDREQUEST._serialized_end=106
  _CENTRAL._serialized_start=108
  _CENTRAL._serialized_end=216
# @@protoc_insertion_point(module_scope)
